# ###Code###
import os
import time
import subprocess
from collections import namedtuple

SimulationData = namedtuple('SimulationData', ['fitness'])
# OutputRow = namedtuple('OutputRow', ['fitness', 'original_genome',
#                                      'built_genome'])


def grab_data(data_file):
    """Returns a list of data that was generated by the simulation

    """
    with open(data_file, 'r') as fr:
        # return SimulationData([line.strip('\n') for line in fr])
        return fr.readline().strip('\n')


def run_simulation(io_file, sim_num):
    """Returns fitness after running the simulation.

    """
    sim_file = '../c++/app'
    folder_switch = '-f' + io_file
    sim_switch = '-n' + str(sim_num)
    data_file = io_file + 'sim_' + str(sim_num) + '.dat'
    check_file = io_file + 'buffer_' + str(sim_num) + '.dat'
    while not os.path.isfile(check_file):
        time.sleep(0.1)
    subprocess.call([sim_file, folder_switch, sim_switch])
    while not os.path.isfile(data_file):
        time.sleep(0.1)
    fitness = grab_data(data_file)
    # print "got fitness from " + str(sim_num)
    os.remove(check_file)
    os.remove(data_file)
    # print "removed junk from " + str(sim_num)
    # return simulation_data.fitness
    return fitness
