# ###Code###
import os
import time
from collections import namedtuple

SimulationData = namedtuple('SimulationData', ['fitness'])
# OutputRow = namedtuple('OutputRow', ['fitness', 'original_genome',
#                                      'built_genome'])


def grab_data(data_file):
    """Returns a list of data that was generated by the simulation

    """
    with open(data_file, 'r') as fr:
        # return SimulationData([line.strip('\n') for line in fr])
        return fr.readline().strip('\n')


def run_simulation():
    """Returns fitness after running the simulation.

    """
    app_file = '../c++/app'
    data_file = '../io/simulation_data.dat'
    check_file = '../io/buffer.dat'
    while not os.path.isfile(check_file):
        time.sleep(0.1)
    os.system(app_file)
    while not os.path.isfile(data_file):
        time.sleep(0.1)
    # simulation_data = grab_data(data_file)
    fitness = grab_data(data_file)
    os.remove(check_file)
    os.remove(data_file)
    # return simulation_data.fitness
    return fitness
